# Generated by Django 2.0.5 on 2018-05-24 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=75)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(default=datetime.date(2018, 7, 23))),
                ('evaluation_type', models.CharField(max_length=100)),
                ('current_grade', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('school_type', models.CharField(choices=[('Charter School', 'Charter School'), ('Private School', 'Private School'), ('Public School', 'Public School')], default='Public School', max_length=20)),
                ('address', models.CharField(default='', max_length=75)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schools', related_query_name='school', to='bullseye.District')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(default='2010-01-01', verbose_name='date of birth')),
                ('mailing_address', models.CharField(blank=True, default='', max_length=75)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('language_preference', models.CharField(choices=[('Arabic', 'Arabic'), ('Chinese', 'Chinese'), ('English', 'English'), ('French', 'French'), ('German', 'German'), ('Japanese', 'Japanese'), ('Portuguese', 'Portuguese'), ('Spanish', 'Spanish'), ('Urdu', 'Urdu')], default='English', max_length=20)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', related_query_name='student', to='bullseye.School')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation', related_query_name='evaluations', to='bullseye.Student'),
        ),
    ]
