# Generated by Django 2.0.5 on 2018-05-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullseye', '0002_auto_20180524_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='object_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
