# Generated by Django 2.0.5 on 2018-05-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullseye', '0003_auto_20180524_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'bullseye'), ('model', 'district')), models.Q(('app_label', 'bullseye'), ('model', 'school')), models.Q(('app_label', 'bullseye'), ('model', 'student')), models.Q(('app_label', 'bullseye'), ('model', 'evaluation')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
