# Generated by Django 2.0.5 on 2018-05-25 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullseye', '0005_auto_20180524_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('view_student', 'Can view student'),)},
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='due_date',
            field=models.DateField(default=datetime.date(2018, 7, 24)),
        ),
    ]
