# Generated by Django 2.0.5 on 2018-05-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullseye', '0006_auto_20180525_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('view_student', 'Can view student and stuff'),)},
        ),
    ]
