# Generated by Django 2.0.5 on 2018-05-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullseye', '0007_auto_20180525_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='evaluations',
            field=models.ManyToManyField(related_name='evaluations', to='bullseye.Evaluation'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='bullseye.Student'),
        ),
    ]
