# Generated by Django 2.0.5 on 2018-05-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullseye', '0008_auto_20180525_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='evaluations',
        ),
    ]
