# Generated by Django 2.0.5 on 2018-05-30 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullseye', '0009_remove_student_evaluations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('view_student', 'Can view student'),)},
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='due_date',
            field=models.DateField(default=datetime.date(2018, 7, 29)),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', related_query_name='evaluation', to='bullseye.Student'),
        ),
    ]
