# Generated by Django 2.0.5 on 2018-05-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullseye', '0010_auto_20180530_1103'),
    ]

    operations = [
        
    ]
