# Generated by Django 2.0.5 on 2018-05-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullseye', '0011_auto_20180530_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='current_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
