# Generated by Django 2.0.5 on 2018-05-31 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullseye', '0012_auto_20180530_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('view_student', 'View student'),)},
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='due_date',
            field=models.DateField(default=datetime.date(2018, 7, 30)),
        ),
    ]
