# Generated by Django 2.0.5 on 2018-05-31 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullseye', '0013_auto_20180531_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('view_student', 'Can view student'),)},
        ),
    ]
