# Generated by Django 2.0.5 on 2018-05-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullseye', '0014_auto_20180531_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluation',
            options={'permissions': (('view_evaluation', 'Can view evaluation'),)},
        ),
    ]
